name: PHPStan Analysis and PHPUnit Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
      branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cache Composer dependencies
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: "psite-web/app/vendor"
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Composer Init
        uses: php-actions/composer@8a65f0d3c6a1d17ca4800491a40b5756a4c164f3 # v6.1.2
        env:
          COMPOSER: "composer.json"
        with:
          php_version: "8.5"
          args: "--ignore-platform-reqs --optimize-autoloader"
          working_dir: "psite-web/app"

      - name: PHPStan Analysis
        run: |
          ./psite-web/app/vendor/bin/phpstan analyse --configuration=psite-web/app/phpstan.neon --memory-limit=1024M

      - name: PHPUnit Tests
        uses: php-actions/phpunit@1789d1964b1bfda259b1cb42a72b65299c2cae35 # v4.0.0
        with:
          version: "11.1"
          memory_limit: "1024M"
          php_version: "8.5"
          bootstrap: "psite-web/app/initialize.php"
          configuration: "phpunit.xml"
