name: PHPStan Analysis and PHPUnit Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
      branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: "psite-web/app/vendor"
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Composer Init
        uses: php-actions/composer@v6
        env:
          COMPOSER: "composer.json"
        with:
          php_version: "8.3"
          args: "--ignore-platform-reqs --optimize-autoloader"
          working_dir: "psite-web/app"

      - name: PHPStan Analysis
        run: |
          ./psite-web/app/vendor/bin/phpstan analyse --configuration=psite-web/app/phpstan.neon --memory-limit=1024M

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v4
        with:
          version: "11.1"
          memmory_limit: "1024M"
          php_version: "8.3"
          bootstrap: "psite-web/app/initialize.php"
          configuration: "phpunit.xml"
