name: PHPStan Analysis and PHPUnit Coverage Report

on:
  push:
    branches: [ "main" ]
  pull_request:
      branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ./psite-web/app/vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Composer Init
        uses: php-actions/composer@v6
        env:
          COMPOSER: "composer.json"
        with:
          php_version: "8.3"
          php_extensions: gd
          args: "--ignore-platform-reqs --optimize-autoloader"
          working_dir: "psite-web/app"

      - name: PHPStan Analysis
        run: |
          ./psite-web/app/vendor/bin/phpstan analyse --configuration=phpstan.neon --memory-limit=1024M